### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Farmer-Pete** [opentracing-contrib/python-pyramid#1]
Hello, what code is this library licensed under?

**Comment by Farmer-Pete** [comment]
Ah, just saw it is licensed under BSD: https://github.com/opentracing-contrib/python-pyramid/blob/031b484e8ea7344c7253d6a68fa27504e98afe07/setup.py#L23

**Comment by tedsuo** [comment]
Thanks @linuxlefty, we should add a license file anyways, just to make it clearer.

**Comment by carlosalberto** [comment]
This is fixed in 43b5919e81681a70c482a027c27083240aa07f57, and we are using the Apache License now (as this is what other projects in OT use or will be using).
